#! /bin/sh

sxhkd &

bspc monitor -d one two three four five six

bspc config border_width         2
bspc config window_gap           0
bspc config top_padding         19

bspc config split_ratio                  0.50
bspc config borderless_monocle           true
bspc config gapless_monocle              true
bspc config focus_follows_pointer        true

bspc config presel_border_color "#00afaf"

bspc rule -a Screenkey manage=off

statusbar &
