#!/bin/sh

. panel_config

Bat() {
	percent=`acpi -b | awk '{gsub(/,/,""); print $4}'`
	time=`acpi -b | awk '{print $5}' | sed 's/:[0-9][0-9]$//g'`
	status=`acpi -b | awk '{gsub(/,/,""); print $3}'`

	if [ $status = "Charging" ]; then
		status="CHG"
	else
		status="BAT"
	fi

	echo "$status: $percent ($time)"
}

Date() {
	date=`date +"%a %d %b %H:%M"`
	echo "$date"
}

Wifi() {
	interface=`iw dev | grep Interface | awk '{print $2}'`
	ssid=`iw "$interface" info | grep ssid | awk '{print $2}'`

	network=$ssid

	echo "NET: $network ($interface)"
}

while true; do
	status=" $(Wifi) | $(Bat) | $(Date) "
	xsetroot -name "$status"
	sleep 1
done
