#! /bin/sh

. panel_config

NORMIFS=$IFS
FIELDIFS=':'
PADDING=' '

while read -r line ; do
    case $line in
        T*)
            # xtitle output
	    title="^fg($COLOR_TITLE_FG) ${line#?}"
            ;;
        W*)
            # bspwm internal state
            wm_infos="$PADDING"
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFfUu]*)
                        # desktops
                        name=${item#?}
                        case $item in
                            O*)
                                # focused occupied desktop
                                FG=$PANEL_COLOR
                                ;;
                            F*)
                                # focused free desktop
                                FG=$PANEL_COLOR
                                ;;
                            U*)
                                # focused urgent desktop
                                FG=$PANEL_COLOR
                                ;;
                            o*)
                                # occupied desktop
                                FG=$PANEL_TEXT_LIGHT
                                # BG=$COLOR_OCUPPIED_BG
                                ;;
                            f*)
                                # free desktop
                                FG=$PANEL_TEXT_DARK
                                # BG=$COLOR_FREE_BG
                                ;;
                            u*)
                                # urgent desktop
                                FG=$PANEL_URGEN_COLOR
                                ;;
                        esac
                        wm_infos="${wm_infos}^fg(${FG})${PADDING}${name}${PADDING}"
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac
    printf "%s\n" "$wm_infos $title"
done
